---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-dev
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/FTP/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-gke-automation
  timeout: 2m0s
  wait: true
